package com.wassabi.model;
// Generated 4 de nov. de 2022 18:56:39 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "Categoria", catalog = "wassabi")
public class Categoria implements java.io.Serializable {

	private Integer categoriaId;
	private String categoriaDescricao;
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Categoria() {
	}

	public Categoria(String categoriaDescricao) {
		this.categoriaDescricao = categoriaDescricao;
	}

	public Categoria(String categoriaDescricao, Set<Produto> produtos) {
		this.categoriaDescricao = categoriaDescricao;
		this.produtos = produtos;
	}

	
    /** 
     * @return Integer
     */
    @Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "categoria_id", unique = true, nullable = false)
	public Integer getCategoriaId() {
		return this.categoriaId;
	}

	
    /** 
     * @param categoriaId
     */
    public void setCategoriaId(Integer categoriaId) {
		this.categoriaId = categoriaId;
	}

	
    /** 
     * @return String
     */
    @Column(name = "categoria_descricao", nullable = false, length = 60)
	public String getCategoriaDescricao() {
		return this.categoriaDescricao;
	}

	
    /** 
     * @param categoriaDescricao
     */
    public void setCategoriaDescricao(String categoriaDescricao) {
		this.categoriaDescricao = categoriaDescricao;
	}

	
    /** 
     * @return Set<Produto>
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	
    /** 
     * @param produtos
     */
    public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

    
    /** 
     * @return String
     */
    @Override
    public String toString() {
        return "Categoria [categoriaId=" + categoriaId + ", categoriaDescricao=" + categoriaDescricao + "]";
    }

}
