package com.wassabi.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "Endereco", catalog = "wassabi")
public class Endereco implements java.io.Serializable {

	private EnderecoId id;
	private Cliente cliente;
	private String enderecoRua;
	private String enderecoBairro;
	private String enderecoCidade;
	private String enderecoEstado;
	private String enderecoPais;
	private String enderecoCep;

	public Endereco() {
	}

	public Endereco(EnderecoId id, Cliente cliente, String enderecoRua, String enderecoBairro, String enderecoCidade,
			String enderecoEstado, String enderecoCep, String enderecoPais) {
		this.id = id;
		this.cliente = cliente;
		this.enderecoRua = enderecoRua;
		this.enderecoBairro = enderecoBairro;
		this.enderecoCidade = enderecoCidade;
		this.enderecoEstado = enderecoEstado;
        this.enderecoCep = enderecoCep;
		this.enderecoPais = enderecoPais;
	}

    public Endereco(Cliente cliente, String enderecoRua, String enderecoBairro, String enderecoCidade,
			String enderecoEstado, String enderecoCep, String enderecoPais) {
	    this.id = new EnderecoId();
		this.cliente = cliente;
		this.enderecoRua = enderecoRua;
		this.enderecoBairro = enderecoBairro;
		this.enderecoCidade = enderecoCidade;
		this.enderecoEstado = enderecoEstado;
		this.enderecoCep = enderecoCep;
		this.enderecoPais = enderecoPais;
	}

	
    /** 
     * @return EnderecoId
     */
    @EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "enderecoId", column = @Column(name = "endereco_id", nullable = false)),
			@AttributeOverride(name = "enderecoCliente", column = @Column(name = "endereco_cliente", nullable = false)) })
	public EnderecoId getId() {
		return this.id;
	}

	
    /** 
     * @param id
     */
    public void setId(EnderecoId id) {
		this.id = id;
	}

	
    /** 
     * @return Cliente
     */
    @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "endereco_cliente", nullable = false, insertable = false, updatable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	
    /** 
     * @param cliente
     */
    public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	
    /** 
     * @return String
     */
    @Column(name = "endereco_rua", nullable = false, length = 30)
	public String getEnderecoRua() {
		return this.enderecoRua;
	}

	
    /** 
     * @param enderecoRua
     */
    public void setEnderecoRua(String enderecoRua) {
		this.enderecoRua = enderecoRua;
	}

	
    /** 
     * @return String
     */
    @Column(name = "endereco_bairro", nullable = false, length = 30)
	public String getEnderecoBairro() {
		return this.enderecoBairro;
	}

	
    /** 
     * @param enderecoBairro
     */
    public void setEnderecoBairro(String enderecoBairro) {
		this.enderecoBairro = enderecoBairro;
	}

	
    /** 
     * @return String
     */
    @Column(name = "endereco_cidade", nullable = false, length = 30)
	public String getEnderecoCidade() {
		return this.enderecoCidade;
	}

	
    /** 
     * @param enderecoCidade
     */
    public void setEnderecoCidade(String enderecoCidade) {
		this.enderecoCidade = enderecoCidade;
	}

	
    /** 
     * @return String
     */
    @Column(name = "endereco_estado", nullable = false, length = 30)
	public String getEnderecoEstado() {
		return this.enderecoEstado;
	}

	
    /** 
     * @param enderecoEstado
     */
    public void setEnderecoEstado(String enderecoEstado) {
		this.enderecoEstado = enderecoEstado;
	}

    /** 
     * @return String
     */
    @Column(name = "endereco_pais", nullable = false, length = 30)
	public String getEnderecoPais() {
		return this.enderecoPais;
	}

	
    /** 
     * @param enderecoPais
     */
    public void setEnderecoPais(String enderecoPais) {
		this.enderecoPais = enderecoPais;
	}

    /** 
     * @return String
     */
    @Column(name = "endereco_cep", nullable = false, length = 10)
	public String getEnderecoCep() {
		return this.enderecoCep;
	}

	
    /** 
     * @param enderecoCep
     */
    public void setEnderecoCep(String enderecoCep) {
		this.enderecoCep = enderecoCep;
	}

    
    /** 
     * @return String
     */
    @Override
    public String toString() {
        return "Endereco [id=" + id + ", cliente=" + cliente + ", enderecoRua=" + enderecoRua + ", enderecoBairro="
                + enderecoBairro + ", enderecoCidade=" + enderecoCidade + ", enderecoEstado=" + enderecoEstado + "]";
    }

}
