package com.wassabi.model;
// Generated 4 de nov. de 2022 18:11:25 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnderecoId generated by hbm2java
 */
@Embeddable
public class EnderecoId implements java.io.Serializable {

	private int enderecoId;
	private int enderecoCliente;

	public EnderecoId() {
	}

	public EnderecoId(int enderecoId, int enderecoCliente) {
		this.enderecoId = enderecoId;
		this.enderecoCliente = enderecoCliente;
	}

	@Column(name = "endereco_id", nullable = false)
	public int getEnderecoId() {
		return this.enderecoId;
	}

	public void setEnderecoId(int enderecoId) {
		this.enderecoId = enderecoId;
	}

	@Column(name = "endereco_cliente", nullable = false)
	public int getEnderecoCliente() {
		return this.enderecoCliente;
	}

	public void setEnderecoCliente(int enderecoCliente) {
		this.enderecoCliente = enderecoCliente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnderecoId))
			return false;
		EnderecoId castOther = (EnderecoId) other;

		return (this.getEnderecoId() == castOther.getEnderecoId())
				&& (this.getEnderecoCliente() == castOther.getEnderecoCliente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEnderecoId();
		result = 37 * result + this.getEnderecoCliente();
		return result;
	}

    @Override
    public String toString() {
        return "EnderecoId [enderecoId=" + enderecoId + ", enderecoCliente=" + enderecoCliente + "]";
    }

}
