package com.wassabi.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendaHasProdutoId generated by hbm2java
 */
@Embeddable
public class VendaHasProdutoId implements java.io.Serializable {

	private int vendaId;
	private int produtoId;

	public VendaHasProdutoId() {
	}

	public VendaHasProdutoId(int vendaId, int produtoId) {
		this.vendaId = vendaId;
		this.produtoId = produtoId;
	}

	
    /** 
     * @return int
     */
    @Column(name = "venda_id", nullable = false)
	public int getVendaId() {
		return this.vendaId;
	}

	
    /** 
     * @param vendaId
     */
    public void setVendaId(int vendaId) {
		this.vendaId = vendaId;
	}

	
    /** 
     * @return int
     */
    @Column(name = "produto_id", nullable = false)
	public int getProdutoId() {
		return this.produtoId;
	}

	
    /** 
     * @param produtoId
     */
    public void setProdutoId(int produtoId) {
		this.produtoId = produtoId;
	}

	
    /** 
     * @param other
     * @return boolean
     */
    public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VendaHasProdutoId))
			return false;
		VendaHasProdutoId castOther = (VendaHasProdutoId) other;

		return (this.getVendaId() == castOther.getVendaId()) && (this.getProdutoId() == castOther.getProdutoId());
	}

	
    /** 
     * @return int
     */
    public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVendaId();
		result = 37 * result + this.getProdutoId();
		return result;
	}

    
    /** 
     * @return String
     */
    @Override
    public String toString() {
        return "VendaHasProdutoId [vendaId=" + vendaId + ", produtoId=" + produtoId + "]";
    }

}
