package model;
// Generated 4 de nov. de 2022 15:43:42 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "Endereco", catalog = "wassabi")
public class Endereco implements java.io.Serializable {

	private Integer enderecoId;
	private String enderecoRua;
	private String enderecoBairro;
	private String enderecoCidade;
	private String enderecoEstado;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Endereco() {
	}

	public Endereco(String enderecoRua, String enderecoBairro, String enderecoCidade, String enderecoEstado) {
		this.enderecoRua = enderecoRua;
		this.enderecoBairro = enderecoBairro;
		this.enderecoCidade = enderecoCidade;
		this.enderecoEstado = enderecoEstado;
	}

	public Endereco(String enderecoRua, String enderecoBairro, String enderecoCidade, String enderecoEstado,
			Set<Cliente> clientes) {
		this.enderecoRua = enderecoRua;
		this.enderecoBairro = enderecoBairro;
		this.enderecoCidade = enderecoCidade;
		this.enderecoEstado = enderecoEstado;
		this.clientes = clientes;
	}

	
    /** 
     * @return Integer
     */
    @Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "endereco_id", unique = true, nullable = false)
	public Integer getEnderecoId() {
		return this.enderecoId;
	}

	
    /** 
     * @param enderecoId
     */
    public void setEnderecoId(Integer enderecoId) {
		this.enderecoId = enderecoId;
	}

	
    /** 
     * @return String
     */
    @Column(name = "endereco_rua", nullable = false, length = 30)
	public String getEnderecoRua() {
		return this.enderecoRua;
	}

	
    /** 
     * @param enderecoRua
     */
    public void setEnderecoRua(String enderecoRua) {
		this.enderecoRua = enderecoRua;
	}

	
    /** 
     * @return String
     */
    @Column(name = "endereco_bairro", nullable = false, length = 30)
	public String getEnderecoBairro() {
		return this.enderecoBairro;
	}

	
    /** 
     * @param enderecoBairro
     */
    public void setEnderecoBairro(String enderecoBairro) {
		this.enderecoBairro = enderecoBairro;
	}

	
    /** 
     * @return String
     */
    @Column(name = "endereco_cidade", nullable = false, length = 30)
	public String getEnderecoCidade() {
		return this.enderecoCidade;
	}

	
    /** 
     * @param enderecoCidade
     */
    public void setEnderecoCidade(String enderecoCidade) {
		this.enderecoCidade = enderecoCidade;
	}

	
    /** 
     * @return String
     */
    @Column(name = "endereco_estado", nullable = false, length = 30)
	public String getEnderecoEstado() {
		return this.enderecoEstado;
	}

	
    /** 
     * @param enderecoEstado
     */
    public void setEnderecoEstado(String enderecoEstado) {
		this.enderecoEstado = enderecoEstado;
	}

	
    /** 
     * @return Set<Cliente>
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	
    /** 
     * @param clientes
     */
    public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
