package model;
// Generated 4 de nov. de 2022 15:43:42 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Venda generated by hbm2java
 */
@Entity
@Table(name = "Venda", catalog = "wassabi")
public class Venda implements java.io.Serializable {

	private Integer vendaId;
	private Cliente cliente;
	private double vendaTotal;
	private Set<VendaHasProduto> vendaHasProdutos = new HashSet<VendaHasProduto>(0);

	public Venda() {
	}

	public Venda(Cliente cliente, double vendaTotal) {
		this.cliente = cliente;
		this.vendaTotal = vendaTotal;
	}

	public Venda(Cliente cliente, double vendaTotal, Set<VendaHasProduto> vendaHasProdutos) {
		this.cliente = cliente;
		this.vendaTotal = vendaTotal;
		this.vendaHasProdutos = vendaHasProdutos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "venda_id", unique = true, nullable = false)
	public Integer getVendaId() {
		return this.vendaId;
	}

	public void setVendaId(Integer vendaId) {
		this.vendaId = vendaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "venda_cliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "venda_total", nullable = false, precision = 30)
	public double getVendaTotal() {
		return this.vendaTotal;
	}

	public void setVendaTotal(double vendaTotal) {
		this.vendaTotal = vendaTotal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "venda")
	public Set<VendaHasProduto> getVendaHasProdutos() {
		return this.vendaHasProdutos;
	}

	public void setVendaHasProdutos(Set<VendaHasProduto> vendaHasProdutos) {
		this.vendaHasProdutos = vendaHasProdutos;
	}

}
